import type { RoomType, Classroom } from "@/types/classroom"

export const defaultRoomTypes: RoomType[] = [
  {
    id: "1",
    name: "Standard Classroom",
    description: "Regular classroom for general subjects",
    color: "#3b82f6",
    defaultCapacity: 35,
    features: ["Whiteboard", "Projector", "Air Conditioning"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Science Laboratory",
    description: "Laboratory for science experiments and practicals",
    color: "#10b981",
    defaultCapacity: 30,
    features: ["Lab Benches", "Fume Hood", "Safety Equipment", "Gas Supply", "Water Supply"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Computer Lab",
    description: "Computer laboratory with workstations",
    color: "#8b5cf6",
    defaultCapacity: 25,
    features: ["Computers", "Network Access", "Projector", "Air Conditioning"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Amphitheatre",
    description: "Large lecture hall with tiered seating",
    color: "#f59e0b",
    defaultCapacity: 150,
    features: ["Tiered Seating", "Audio System", "Large Screen", "Stage", "Microphones"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Art Studio",
    description: "Creative space for art and design classes",
    color: "#ec4899",
    defaultCapacity: 20,
    features: ["Art Supplies Storage", "Natural Light", "Easels", "Sink", "Ventilation"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Music Room",
    description: "Soundproof room for music classes and practice",
    color: "#06b6d4",
    defaultCapacity: 25,
    features: ["Soundproofing", "Piano", "Music Stands", "Audio Equipment", "Storage"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "7",
    name: "Gymnasium",
    description: "Large indoor sports facility",
    color: "#ef4444",
    defaultCapacity: 100,
    features: ["Sports Equipment", "Changing Rooms", "First Aid", "Storage", "Scoreboard"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]

export const defaultClassrooms: Classroom[] = [
  {
    id: "1",
    name: "Room 101",
    code: "R101",
    roomTypeId: "1",
    capacity: 35,
    floor: "1st Floor",
    building: "Main Building",
    features: ["Whiteboard", "Projector", "Air Conditioning"],
    equipment: ["Chairs", "Desks", "Teacher's Desk"],
    isActive: true,
    notes: "Recently renovated classroom",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Room 102",
    code: "R102",
    roomTypeId: "1",
    capacity: 35,
    floor: "1st Floor",
    building: "Main Building",
    features: ["Whiteboard", "Projector", "Air Conditioning"],
    equipment: ["Chairs", "Desks", "Teacher's Desk"],
    isActive: true,
    notes: "",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Science Lab A",
    code: "SLA",
    roomTypeId: "2",
    capacity: 30,
    floor: "2nd Floor",
    building: "Science Block",
    features: ["Lab Benches", "Fume Hood", "Safety Equipment", "Gas Supply", "Water Supply"],
    equipment: ["Lab Equipment", "Safety Gear", "Microscopes"],
    isActive: true,
    notes: "Chemistry and Biology lab",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Computer Lab",
    code: "CL1",
    roomTypeId: "3",
    capacity: 25,
    floor: "3rd Floor",
    building: "Technology Block",
    features: ["Computers", "Network Access", "Projector", "Air Conditioning"],
    equipment: ["30 Computers", "Server", "Printer"],
    isActive: true,
    notes: "Latest computers with high-speed internet",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Main Auditorium",
    code: "AUD1",
    roomTypeId: "4",
    capacity: 150,
    floor: "Ground Floor",
    building: "Main Building",
    features: ["Tiered Seating", "Audio System", "Large Screen", "Stage", "Microphones"],
    equipment: ["Sound System", "Lighting", "Podium"],
    isActive: true,
    notes: "Used for assemblies and large lectures",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]
